# makefile for building haarcascade

CC=gcc
RM=rm -f
CFLAGS=-O3 -Wall -Wconversion -pedantic $(EXTRA_FLAGS) $(INCLUDES)
INCLUDES=
LIBS=-lm -lpng -ljpeg -lpthread
OBJS=main.o trainer.o cascade.o boosting.o samples.o csv_reader.o \
     features.o image.o utils.o window.o random.o thread_pool.o \
     stopwatch.o cpa.o detector.o
TARGET=haarcascade

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $^ $(LIBS) $(EXTRA_LD_FLAGS) -o $@

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean

clean:
	$(RM) $(TARGET) $(OBJS)

# automatically generated by `gcc -MM *.c`
# DO NOT DELETE
boosting.o: boosting.c boosting.h utils.h
cascade.o: cascade.c cascade.h features.h image.h window.h utils.h
cpa.o: cpa.c cpa.h utils.h
csv_reader.o: csv_reader.c csv_reader.h utils.h
detector.o: detector.c detector.h image.h window.h cascade.h features.h \
 samples.h thread_pool.h utils.h
features.o: features.c features.h image.h window.h utils.h
image.o: image.c image.h window.h utils.h
main.o: main.c trainer.h boosting.h cpa.h detector.h image.h window.h \
 cascade.h features.h samples.h thread_pool.h random.h utils.h
random.o: random.c random.h
samples.o: samples.c samples.h window.h csv_reader.h utils.h
stopwatch.o: stopwatch.c stopwatch.h
thread_pool.o: thread_pool.c thread_pool.h utils.h
trainer.o: trainer.c trainer.h boosting.h cpa.h detector.h image.h \
 window.h cascade.h features.h samples.h thread_pool.h stopwatch.h \
 random.h utils.h
utils.o: utils.c utils.h
window.o: window.c window.h utils.h
